[env:genericSTM32F412RG]
platform = ststm32
board = genericSTM32F412RG
framework = cmsis

upload_protocol = stlink
debug_tool = stlink

board_build.ldscript = linker/app.ld
board_upload.offset_address = 0x08008000

board_build.fpu = fpv4-sp-d16
board_build.float-abi = hard

lib_deps =
  FreeRTOS-Kernel

build_flags =
  -DSTM32F412xx
  -Iinclude